version: '3.1'
services:
  spboot-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=haydikodlayalim
      - RABBITMQ_DEFAULT_PASS=haydikodlayalim

